//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackathonWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.RequestFollowUps = new HashSet<RequestFollowUp>();
        }
    
        public int ID { get; set; }
        public int PersonID { get; set; }
        public string Type { get; set; }
        public string Comment { get; set; }
        public int VitalSignA { get; set; }
        public int VitalSignB { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> CallerID { get; set; }
        public string GPS { get; set; }
        public string Status { get; set; }
    
        public virtual Paramedic Paramedic { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestFollowUp> RequestFollowUps { get; set; }
    }
}
